class MandelbrotSet:
    def __init__(self, grid_size: int) -> None:...
    def make_grid(self, re_min: float, re_max: float, im_min: float, im_max: float, max_iter: int) -> int: ...

def is_in_mandelbrot_set(re: float, im: float, max_iter: int) -> int: ...